version: '3.8'

services:
  email-delivery-monitor:
    build: .
    container_name: email-delivery-monitor
    restart: unless-stopped

    # Environment variables - Service Account Configuration
    environment:
      - OFFICE365_TENANT_ID=your_tenant_id_here
      - OFFICE365_CLIENT_ID=your_client_id_here
      - OFFICE365_CLIENT_SECRET=your_client_secret_here
      - OFFICE365_SENDER_EMAIL=email-monitor@innov8it.com.au
      - GMAIL_RECIPIENT_EMAIL=your_gmail_email_here
      - ZABBIX_SERVER=10.10.10.70
      - ZABBIX_PORT=10051
      - ZABBIX_HOST=email-monitor
      - TEST_INTERVAL=60
      - TIMEOUT_SECONDS=300
      - LOG_LEVEL=INFO
      - SKIP_GMAIL_SETUP=true

    # Volume mounts - these will be created automatically
    volumes:
      - email-monitor-logs:/app/logs
      - email-monitor-credentials:/app/credentials

    # Network configuration
    networks:
      - monitoring

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import os; exit(0 if os.path.exists(\"/app/logs/email_delivery_monitor.log\") else 1)'"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  monitoring:
    driver: bridge
    name: monitoring-network

volumes:
  email-monitor-logs:
    driver: local
  email-monitor-credentials:
    driver: local
